table Month

	column month
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: month

	column year
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: year

	column month_label
		dataType: string
		sortByColumn: month_index
		summarizeBy: none
		sourceColumn: month_label

	column fy_start
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: fy_start

	column fiscal_year
		dataType: string
		summarizeBy: none
		sourceColumn: fiscal_year

	column month_index
		dataType: int64
		formatString: 0
		isHidden
		summarizeBy: none
		sourceColumn: month_index

	column month_end
		dataType: dateTime
		formatString: Short Date
		isHidden
		summarizeBy: none
		sourceColumn: month_end

	partition Month = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_month.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Typed columns" = Table.TransformColumnTypes(
				        #"Promoted headers",
				        {
						{"month", type date},
						{"year", Int64.Type},
						{"month_label", type text},
						{"fy_start", Int64.Type},
						{"fiscal_year", type text},
						{"month_index", Int64.Type},
						{"month_end", type date}
				        },
				        "en-US"
				    )
				in
				    #"Typed columns"
